services:
  postgres:
    image: postgres:16
    container_name: workops-postgres
    environment:
      POSTGRES_USER: workops
      POSTGRES_PASSWORD: workops
      POSTGRES_DB: workops
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workops -d workops"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer:4
    container_name: workops-adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: workops-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
      # Para callbacks de Google y CORS, adapta el hostname si usas reverse proxy:
      KC_HOSTNAME: http://localhost:8080
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-workops.json:/opt/keycloak/data/import/realm-workops.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      ASPNETCORE_URLS: http://+:8085
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=workops;Username=workops;Password=workops
      Auth__Authority: http://localhost:8080/realms/workops
      Auth__InternalMetadata: http://localhost:8080/realms/workops/.well-known/openid-configuration
      AUTH_VALIDISSUER: "http://host.docker.internal:8080/realms/workops"
      Auth__Audience: workops-api
      Auth__RequireHttps: "false"
      Cors__AllowedOrigins__0: http://localhost:8086
      Cors__AllowedOrigins__1: http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

  workops-frontend:
    build:
      context: ./client
    ports:
      - "8086:80"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://host.docker.internal:8085
      - VITE_TOKEN_URL=http://host.docker.internal:8080/realms/workops/protocol/openid-connect/token
      - VITE_CLIENT_ID=workops-spa

volumes:
  pg_data:
  client_node_modules:

